env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jest
  - '@typescript-eslint'
rules: {
    # suppress errors for missing 'import React' in files
    'react/react-in-jsx-scope': 'off',
    # allow jsx syntax in js files (for next.js project)
    'react/jsx-filename-extension':
      [1, { 'extensions': ['.js', '.jsx', '.tsx'] }],
  }
settings:
  {
    'import/resolver':
      { node: { paths: ['src'], extensions: ['.js', '.jsx', '.ts', '.tsx'] } },
    react: { version: 'detect' },
  }
